### PR TITLE
Handle pymysql OperationalError in worker script

### PR DESCRIPTION
**Pull request by gvozdetsky**
An exception clause for pymysql's OperationalError has been included in the worker script. Query run (qrun) status is now updated to 'failed' and logged for operational exceptions, thus improving error handling and traceability.

Bug: T365136

### CODE REVIEW

**Comment by gvozdetsky** [comment]
Bug: T365136

File: quarry/web/worker.py [hunk 1]
```diff
@@ -148,6 +148,13 @@ def run_query(query_run_id):
             celery_log.info("Stopped run for qrun:%s", qrun.id)
         else:
             write_error(qrun, e.args[1])
+    except pymysql.err.OperationalError as e:
+        qrun.status = QueryRun.STATUS_FAILED
```
Comment (siddharthvp) [inline quarry/web/worker.py:152]: I think it's also worth surfacing the error message to the user per the comment on line 141. Otherwise, the UI would just say it failed, with no explanation. 

We could just use the write_error() function here.

File: quarry/web/worker.py [hunk 2]
```diff
@@ -148,6 +148,13 @@ def run_query(query_run_id):
             celery_log.info("Stopped run for qrun:%s", qrun.id)
         else:
             write_error(qrun, e.args[1])
+    except pymysql.err.OperationalError as e:
```
Comment (siddharthvp) [inline quarry/web/worker.py:151]: I'm not sure if this would work. I believe the `pymysql.err.OperationalError` raised is being wrapped by an `sqlalchemy.exc.OperationalError`. We could just catch `Exception`, so that everything is covered.

File: quarry/web/worker.py [hunk 3]
```diff
@@ -148,6 +148,13 @@ def run_query(query_run_id):
...
+        qrun.status = QueryRun.STATUS_FAILED
+        conn.session.add(qrun)
+        conn.session.commit()
+        celery_log.error(
+            "OperationalError for qrun:%s, error: %s", qrun.id, str(e)
```
Comment (siddharthvp) [inline quarry/web/worker.py:156]: I wonder if there are better ways to stringify errors than `str(e)`? May be something from the [traceback module](https://docs.python.org/3/library/traceback.html)?

File: quarry/web/worker.py (hunk 1 above)
Comment (gvozdetsky) [reply quarry/web/worker.py:153]: write_error() is just:
```
qrun.status = QueryRun.STATUS_FAILED
    qrun.extra_info = json.dumps({"error": error})
    conn.session.add(qrun)
    conn.session.commit()
    celery_log.info(
        "Completed run for qrun:%s with failure: %s", qrun.id, error
    )
```
which we already do. But I added `qrun.extra_info = json.dumps({"error": e.args[1]})` here too

File: quarry/web/worker.py (hunk 2 above)
Comment (gvozdetsky) [reply quarry/web/worker.py]: Thanks, changed to catching all Exceptions

File: quarry/web/worker.py (hunk 3 above)
Comment (gvozdetsky) [reply quarry/web/worker.py]: Added traceback

```
tb_str = "".join(
            traceback.format_exception(
                etype=type(e), value=e, tb=e.__traceback__
            )
        )
        celery_log.error(
            "OperationalError for qrun:%s, error: %s, traceback: %s",
            qrun.id,
            str(e),
            tb_str,
        )
```

File: quarry/web/worker.py [hunk 4]
```diff
@@ -148,6 +149,22 @@ def run_query(query_run_id):
...
         else:
             write_error(qrun, e.args[1])
+    except Exception as e:
+        qrun.status = QueryRun.STATUS_FAILED
+        qrun.extra_info = json.dumps({"error": e.args[1]})
+        conn.session.add(qrun)
+        conn.session.commit()
+        tb_str = "".join(
+            traceback.format_exception(
+                etype=type(e), value=e, tb=e.__traceback__
```
Comment (siddharthvp) [inline quarry/web/worker.py:159]: This works in python 3.7 (current version in prod), but fails on python 3.10 with `TypeError: format_exception() got an unexpected keyword argument 'etype'`. Just `traceback.format_exception(e)` gives the same output in python 3.10.

Please add a comment noting the above as we'll need to update it while upgrading python.

File: quarry/web/worker.py [hunk 5]
```diff
@@ -148,6 +149,22 @@ def run_query(query_run_id):
             celery_log.info("Stopped run for qrun:%s", qrun.id)
         else:
             write_error(qrun, e.args[1])
+    except Exception as e:
+        qrun.status = QueryRun.STATUS_FAILED
+        qrun.extra_info = json.dumps({"error": e.args[1]})
```
[the remark this answers is not in the document]
Comment (siddharthvp) [reply quarry/web/worker.py]: Perhaps we can use `repr(e)`.

[the remark this answers is not in the document]
Comment (siddharthvp) [reply quarry/web/worker.py]: Done

File: quarry/web/worker.py (hunk 4 above)
Comment (siddharthvp) [reply quarry/web/worker.py]: I've changed this to check current python version using `sys.version_info` and format accordingly, to avoid any inconvenience when we upgrade python.

**Review by siddharthvp — APPROVED** [review]
Working fine.

**Review by siddharthvp — APPROVED** [review]
(rebased)

**Comment by siddharthvp** [comment]
@vivian-rook -  could you deploy this one as well?
